name: product_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17
  firebase_remote_config: ^3.0.15
  firebase_ui_auth: ^1.1.17
  firebase_ui_oauth_facebook: ^1.0.24
  firebase_ui_oauth_google: ^1.0.24
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  geolocator: ^9.0.2
  go_router: ^6.5.1
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.5
  google_sign_in: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
