// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO1HWcbOnDBm7HZb4_nmScqMvlSIYlQ0g',
    appId: '1:652800919583:web:9ac4a60dce2e6f452eed2a',
    messagingSenderId: '652800919583',
    projectId: 'productview-a8b21',
    authDomain: 'productview-a8b21.firebaseapp.com',
    storageBucket: 'productview-a8b21.appspot.com',
    measurementId: 'G-HWMHBR66R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK5Ug9fFUbC4-VNh5DQ4kjCaMEeQh58P0',
    appId: '1:652800919583:android:a337a99f9e297f1e2eed2a',
    messagingSenderId: '652800919583',
    projectId: 'productview-a8b21',
    storageBucket: 'productview-a8b21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYmwuIA2Yq5uPykRUYWN7XfuRnVd88tbo',
    appId: '1:652800919583:ios:d70498100e1be8682eed2a',
    messagingSenderId: '652800919583',
    projectId: 'productview-a8b21',
    storageBucket: 'productview-a8b21.appspot.com',
    androidClientId: '652800919583-17eomeck717pao5297s9t1hhfm3j38jr.apps.googleusercontent.com',
    iosClientId: '652800919583-b3g6rcc2qo0ciujpjgt8j0pcja71rles.apps.googleusercontent.com',
    iosBundleId: 'com.example.productList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYmwuIA2Yq5uPykRUYWN7XfuRnVd88tbo',
    appId: '1:652800919583:ios:d70498100e1be8682eed2a',
    messagingSenderId: '652800919583',
    projectId: 'productview-a8b21',
    storageBucket: 'productview-a8b21.appspot.com',
    androidClientId: '652800919583-17eomeck717pao5297s9t1hhfm3j38jr.apps.googleusercontent.com',
    iosClientId: '652800919583-b3g6rcc2qo0ciujpjgt8j0pcja71rles.apps.googleusercontent.com',
    iosBundleId: 'com.example.productList',
  );
}
